name: assingment_cover_genaret
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  printing: ^5.11.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# আইকন কনফিগারেশন (নিশ্চিত করুন assets ফোল্ডারে icon.png ফাইলটি আছে)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # আপনার অ্যাপের ভেতরে লোগো ব্যবহারের জন্য নিচের অংশটুকু আন-কমেন্ট করে দিলাম
  assets:
    - assets/icon.png